[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-package-lock --legacy-peer-deps"

[deploy]
startCommand = "node connect.js"
restartPolicyType = "ALWAYS"
healthCheckPath = "/"
healthCheckTimeout = 120
